variable "aws_account_id" {}
variable "environment" {}
variable "project_name" {}
variable "github_token" {}
variable "buildspec_location" {}
variable "registry_name" {}
variable "ecs_service_web_name" {}
variable "ecs_cluster_name" {}
variable "ecs_worker_service_name" {}
variable "git_branch_to_track" {}
