---
AlertRun:
  subscription:
    ColumnPresenceChecker:
      enabled: false
EmergencyLoginKey:
  publisher:
    ColumnPresenceChecker:
      enabled: false
FailedImportedVacancy:
  source:
    NullConstraintChecker:
      enabled: false
Feedback:
  relevant_to_user:
    ThreeStateBooleanChecker:
      enabled: false
InvitationToApply:
  invited_by:
    ColumnPresenceChecker:
      enabled: false
  jobseeker:
    ColumnPresenceChecker:
      enabled: false
  vacancy:
    ColumnPresenceChecker:
      enabled: false
JobApplication:
  employment_history_section_completed:
    ThreeStateBooleanChecker:
      enabled: false
  jobseeker:
    ColumnPresenceChecker:
      enabled: false
  qualifications_section_completed:
    ThreeStateBooleanChecker:
      enabled: false
  vacancy:
    ColumnPresenceChecker:
      enabled: false
JobPreferences:
  jobseeker_profile:
    ColumnPresenceChecker:
      enabled: false
JobPreferences::Location:
  area:
    NullConstraintChecker:
      enabled: false
  name:
    NullConstraintChecker:
      enabled: false
  radius:
    NullConstraintChecker:
      enabled: false
Jobseeker:
  email:
    ColumnPresenceChecker:
      enabled: false
JobseekerProfile:
  jobseeker:
    ColumnPresenceChecker:
      enabled: false
  requested_hidden_profile:
    ThreeStateBooleanChecker:
      enabled: false
LocalAuthorityPublisherSchool:
  publisher_preference:
    ColumnPresenceChecker:
      enabled: false
  school:
    ColumnPresenceChecker:
      enabled: false
LocationPolygon:
  name:
    NullConstraintChecker:
      enabled: false
Notification:
  type:
    NullConstraintChecker:
      enabled: false
OrganisationPublisher:
  organisation:
    ColumnPresenceChecker:
      enabled: false
  publisher:
    ColumnPresenceChecker:
      enabled: false
OrganisationPublisherPreference:
  organisation:
    ColumnPresenceChecker:
      enabled: false
  publisher_preference:
    ColumnPresenceChecker:
      enabled: false
OrganisationVacancy:
  organisation:
    ColumnPresenceChecker:
      enabled: false
  vacancy:
    ColumnPresenceChecker:
      enabled: false
PersonalDetails:
  phone_number_provided:
    ThreeStateBooleanChecker:
      enabled: false
  right_to_work_in_uk:
    ThreeStateBooleanChecker:
      enabled: false
PublisherPreference:
  organisation:
    ColumnPresenceChecker:
      enabled: false
  publisher:
    ColumnPresenceChecker:
      enabled: false
Qualification:
  finished_studying:
    ThreeStateBooleanChecker:
      enabled: false
  qualification_results:
    ForeignKeyCascadeChecker:
      enabled: false
SavedJob:
  jobseeker:
    ColumnPresenceChecker:
      enabled: false
  vacancy:
    ColumnPresenceChecker:
      enabled: false
SchoolGroupMembership:
  do_not_delete:
    ThreeStateBooleanChecker:
      enabled: false
  school:
    ColumnPresenceChecker:
      enabled: false
  school_group:
    ColumnPresenceChecker:
      enabled: false
Subscription:
  active:
    ThreeStateBooleanChecker:
      enabled: false
Vacancy:
  benefits:
    ThreeStateBooleanChecker:
      enabled: false
  contact_number_provided:
    ThreeStateBooleanChecker:
      enabled: false
  enable_job_applications:
    ThreeStateBooleanChecker:
      enabled: false
  further_details_provided:
    ThreeStateBooleanChecker:
      enabled: false
  google_index_removed:
    ThreeStateBooleanChecker:
      enabled: false
  include_additional_documents:
    ThreeStateBooleanChecker:
      enabled: false
  safeguarding_information_provided:
    ThreeStateBooleanChecker:
      enabled: false
  school_visits:
    ThreeStateBooleanChecker:
      enabled: false
  starts_asap:
    ThreeStateBooleanChecker:
      enabled: false
