inherit_mode:
  merge:
    - Exclude

inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
#  Avoid the 'default' config as it disables lots of useful metrics
#    - config/default.yml
    - config/layout.yml
    - config/naming.yml
    - config/style.yml
    - config/rake.yml
    - config/rails.yml
    - config/rspec.yml

require:
  - rubocop-rspec_rails

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  UseCache: true
  Exclude:
    - "bin/**"
    - "config.ru"
    - "tmp/**/*"
    - "db/schema.rb"
    - "db/migrate/2017*"
    - "db/migrate/2018*"
    - "db/migrate/2019*"
    - "db/migrate/2020*"
    - "db/migrate/2021*"
    - "db/migrate/2022*"
    - "db/migrate/2023*"
    - "db/migrate/202401*"
    - "db/migrate/202402*"
    - "db/migrate/202403*"
    - "db/migrate/202404*"
    - "db/migrate/202405*"
    - "db/migrate/202406*"
    - "db/migrate/202407*"
    - "db/migrate/202408*"
    - "vendor/**/*"
    - "node_modules/**/*"

  DisplayCopNames:
    Enabled: true

  ExtraDetails:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

##
# Team Style conventions

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/Debugger:
  DebuggerMethods:
    Capybara:
      - saop
      - save_and_open_page
      - save_and_open_screenshot

Lint/UselessMethodDefinition:
  Exclude:
    - "app/controllers/**/*_controller.rb"

# List as per https://docs.rubocop.org/rubocop/cops_naming.html#namingmethodparametername
# plus `as`.
Naming/MethodParameterName:
  AllowedNames:
    - as
    - at
    - by
    - db
    - id
    - in
    - io
    - ip
    - of
    - on
    - os
    - pp
    - to

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either

# This is incompatible with our other migration checks
Rails/BulkChangeTable:
  Enabled: false

##
# Tech Debt
# TODO: `rubocop-govuk` previously had all these metrics disabled as they are "just heuristics".
# They're not brilliant metrics, but they *can* point to some degree of accidental complexity.
# We should consider slowly moving closer to the default settings.

Metrics/AbcSize:
  Max: 31 # Default 17
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 18 # Default 7
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 19 # Default 10
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 194
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ModuleLength:
  Exclude:
    - "app/helpers/**/*"
    - "spec/**/*"

Metrics/ParameterLists:
  Max: 7 # Default 5

Metrics/PerceivedComplexity:
  Max: 18 # Default 8
  Exclude:
    - "spec/**/*"
