inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
    TargetRubyVersion: 2.6
    Exclude:
      - 'db/migrate/**/*'
      - 'db/schema.rb'
      - 'bin/**/*'
      - 'config/initializers/simple_form.rb'
      - 'config/initializers/assets.rb'
      - 'vendor/**/*'
      - 'node_modules/**/*'
      - 'tmp/**/*'

Rails:
    Enabled: true

Rails/HasManyOrHasOneDependent:
    Enabled: false

Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Layout/TrailingEmptyLines:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/StringLiterals:
    EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/AbcSize:
    Max: 25
    Exclude:
      - 'spec/**/*'
      - 'app/jobs/performance_platform_feedback_queue_job.rb'
      - 'lib/export_tables_to_big_query.rb'

Metrics/ModuleLength:
    Exclude:
      - 'spec/support/vacancy_helpers.rb'

Metrics/LineLength:
    Max: 120
    Exclude:
      - 'config/initializers/performance_platform.rb'

Metrics/BlockLength:
    Max: 40
    Exclude:
      - 'spec/**/*'
      - 'config/routes.rb'

Layout/EmptyLinesAroundAccessModifier:
    Enabled: false

Layout/SpaceInsideBlockBraces:
    EnforcedStyleForEmptyBraces: no_space

Layout/IndentationWidth:
    Enabled: false
