require:
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**"
    - "config.ru"
    - "tmp/**/*"
    - "db/schema.rb"
    - "db/migrate/20*"
    - "vendor/**/*"
    - "node_modules/**/*"

  DisplayCopNames:
    Enabled: true

  ExtraDetails:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

##
# Team Style conventions

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

##
# Temporary rules
# TODO: These have a lot of warnings, or relate to unfinished stylistic discussions within the team

Lint/MissingSuper:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

##
# Tech Debt
# TODO: `rubocop-govuk` previously had all these metrics disabled as they are "just heuristics".
# They're not brilliant metrics, but they *can* point to some degree of accidental complexity.
# We should consider slowly moving closer to the default settings.

Metrics/AbcSize:
  Max: 40 # Default 17
  Exclude:
    - "config/**/*"
    - "lib/**/*"
    - "spec/**/*"

Metrics/BlockLength:
  Max: 75 # Default 25
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 200 # Default 100

Metrics/CyclomaticComplexity:
  Max: 20 # Default 7
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 18 # Default 10
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ModuleLength:
  Max: 210 # Default 100

Metrics/ParameterLists:
  Max: 8 # Default 5

Metrics/PerceivedComplexity:
  Max: 20 # Default 8
  Exclude:
    - "spec/**/*"
