AllCops:
    TargetRubyVersion: 2.6
    Exclude:
      - 'db/migrate/**/*'
      - 'db/schema.rb'
      - 'bin/**/*'
      - 'config/initializers/simple_form.rb'
      - 'config/initializers/assets.rb'

Rails:
    Enabled: true

Rails/HasManyOrHasOneDependent:
    Enabled: false

Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Layout/TrailingBlankLines:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/AbcSize:
    Max: 25
    Exclude:
      - 'spec/**/*'
      - 'app/jobs/performance_platform_feedback_queue_job.rb'

Metrics/ModuleLength:
    Exclude:
      - 'spec/support/vacancy_helpers.rb'

Metrics/LineLength:
    Max: 120
    Exclude:
      - 'config/initializers/performance_platform.rb'

Metrics/BlockLength:
    Max: 40
    Exclude:
      - 'spec/**/*'
      - 'config/routes.rb'
