require:
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**"
    - "config.ru"
    - "tmp/**/*"
    - "db/schema.rb"
    - "db/migrate/20*"
    - "vendor/**/*"
    - "node_modules/**/*"

  DisplayCopNames:
    Enabled: true

  ExtraDetails:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

##
# Team Style conventions

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/Debugger:
  DebuggerMethods:
    Capybara:
      - saop
      - save_and_open_page
      - save_and_open_screenshot

# List as per https://docs.rubocop.org/rubocop/cops_naming.html#namingmethodparametername
# plus `as`.
Naming/MethodParameterName:
  AllowedNames:
    - as
    - at
    - by
    - db
    - id
    - in
    - io
    - ip
    - of
    - on
    - os
    - pp
    - to

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

##
# Temporary rules
# TODO: These have a lot of warnings, or relate to unfinished stylistic discussions within the team

Lint/MissingSuper:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/BlockForwarding:
  # We do want to use this, but are blocked by Brakeman's parser not supporting 3.1 syntax
  Enabled: false

Style/HashSyntax:
  # This causes some issues in Slim templates that require a wider style discussion, and is
  # currently unsupported by Brakeman's parser
  Enabled: false

##
# Tech Debt
# TODO: `rubocop-govuk` previously had all these metrics disabled as they are "just heuristics".
# They're not brilliant metrics, but they *can* point to some degree of accidental complexity.
# We should consider slowly moving closer to the default settings.

Metrics/AbcSize:
  Max: 31 # Default 17
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/BlockLength:
  Max: 25 # Default 25
  Exclude:
    - "config/**/*"
    - "spec/**/*"
    - "app/models/concerns/indexable.rb"

Metrics/ClassLength:
  Max: 166 # Default 100

Metrics/CyclomaticComplexity:
  Max: 18 # Default 7
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 18 # Default 10
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ModuleLength:
  Max: 113 # Default 100
  Exclude:
    - "spec/**/*"

Metrics/ParameterLists:
  Max: 7 # Default 5

Metrics/PerceivedComplexity:
  Max: 18 # Default 8
  Exclude:
    - "spec/**/*"
