azure_storage_documents:
  service: AzureBlob
  storage_account_name: <%= ENV["DOCUMENTS_AZURE_STORAGE_ACCOUNT_NAME"] %>
  storage_access_key: <%= ENV["DOCUMENTS_AZURE_STORAGE_ACCESS_KEY"] %>
  container: documents

azure_storage_images_and_logos:
  service: AzureBlob
  storage_account_name: <%= ENV["IMAGES_LOGOS_AZURE_STORAGE_ACCOUNT_NAME"] %>
  storage_access_key: <%= ENV["IMAGES_LOGOS_AZURE_STORAGE_ACCESS_KEY"] %>
  container: images-logos
