---
AUTHENTICATION_FALLBACK: true
BIG_QUERY_DATASET: production_dataset
CLOUD_STORAGE_BUCKET: tvs_production
DFE_SIGN_IN_ISSUER: https://oidc.signin.education.gov.uk
DFE_SIGN_IN_REDIRECT_URL: https://teaching-vacancies.service.gov.uk/auth/dfe/callback
DFE_SIGN_IN_URL: https://api.signin.education.gov.uk
DISABLE_EXPENSIVE_JOBS: false
DOMAIN: teaching-vacancies.service.gov.uk
FEATURE_COOKIES_BANNER: true
FEATURE_EMAIL_ALERTS: true
FEATURE_MULTI_SCHOOL_JOBS: false
FEATURE_READ_ONLY: false
FEATURE_SCHOOL_GROUP_JOBS: true
GOOGLE_ANALYTICS_PROFILE_ID: ga:171744074
GOOGLE_CLOUD_PLATFORM_PROJECT_ID: teacher-vacancy-service
OPENSSL_CONF: /etc/ssl/
RACK_ENV: production
RAILS_ENV: production
RAILS_LOG_TO_STDOUT: true
RAILS_MAX_THREADS: 5
RAILS_SERVE_STATIC_FILES: true
ROLLBAR_ENV: production
SKYLIGHT_ENABLED: true
SKYLIGHT_ENV: production
SKYLIGHT_IGNORED_ENDPOINTS: ApplicationController#check
