---
APP_ROLE: production
AUTHENTICATION_FALLBACK: false
BIG_QUERY_DATASET: production_dataset
DFE_SIGN_IN_ISSUER: https://oidc.signin.education.gov.uk
DFE_SIGN_IN_REDIRECT_URL: https://teaching-vacancies.service.gov.uk/auth/dfe/callback
DFE_SIGN_IN_REGISTRATION_URL: https://profile.signin.education.gov.uk/register
DFE_SIGN_IN_URL: https://api.signin.education.gov.uk
DISABLE_EXPENSIVE_JOBS: false
DOMAIN: teaching-vacancies.service.gov.uk
ENFORCE_LOCAL_AUTHORITY_ALLOWLIST: true
GOOGLE_TAG_MANAGER_CONTAINER_ID: GTM-P5L2QHV
MALLOC_ARENA_MAX: 2
RAILS_ENV: production
RAILS_LOG_TO_STDOUT: true
RAILS_MAX_THREADS: 5
RAILS_SERVE_STATIC_FILES: true
SESSION_DAYS_TRIM_THRESHOLD: 14
SKYLIGHT_ENABLED: true
SKYLIGHT_ENABLE_SIDEKIQ: true
SKYLIGHT_ENV: production
SKYLIGHT_IGNORED_ENDPOINTS: ApplicationController#check
