---
APP_ROLE: production
AUTHENTICATION_FALLBACK: false
BIG_QUERY_DATASET: production_dataset
DFE_SIGN_IN_ISSUER: https://oidc.signin.education.gov.uk
DFE_SIGN_IN_REDIRECT_URL: https://teaching-vacancies.service.gov.uk/publishers/auth/dfe/callback
DFE_SIGN_IN_URL: https://api.signin.education.gov.uk
DISABLE_EXPENSIVE_JOBS: false
DOMAIN: teaching-vacancies.service.gov.uk
ENFORCE_LOCAL_AUTHORITY_ALLOWLIST: true
FEATURE_JOBSEEKER_APPLICATIONS: true
GOOGLE_ANALYTICS_PROFILE_ID: ga:171744074
MALLOC_ARENA_MAX: 2
RAILS_ENV: production
RAILS_LOG_TO_STDOUT: true
RAILS_MAX_THREADS: 5
RAILS_SERVE_STATIC_FILES: true
ROLLBAR_ENV: production
SKYLIGHT_ENABLED: true
SKYLIGHT_ENABLE_SIDEKIQ: true
SKYLIGHT_ENV: production
SKYLIGHT_IGNORED_ENDPOINTS: ApplicationController#check
