name: deploy workflow
description: deploy's application

inputs:
  environment:
    description: Environment
    required: true
  tag:
    description: Docker tag
    required: true
  pr_id:
    description: Pull Request
    required: false
  aws-access-key-id:
    description: AWS-ID
    required: true
  aws-secret-access-key:
    description: AWS-KEY
    required: true
  azure-client-id:
    description: Azure service principal or managed identity client ID when using OIDC
    required: true
  azure-subscription-id:
    description: Azure service principal or managed identity subscription ID when using OIDC
    required: true
  azure-tenant-id:
    description: Azure service principal or managed identity tenant ID when using OIDC
    required: true


runs:
  using: composite
  steps:

    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-west-2
        role-to-assume: Deployments
        role-duration-seconds: 3600
        role-skip-session-tagging: true

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}

    - uses: google-github-actions/auth@v2
      with:
        project_id: teacher-vacancy-service
        workload_identity_provider: projects/689616473831/locations/global/workloadIdentityPools/teaching-vacancies/providers/teaching-vacancies

    - name: Pin Terraform version
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.1

    - name: Set environment variables for review
      if: startsWith( inputs.environment, 'review')
      shell: bash
      run: |
        PARAMETER_STORE_ENVIRONMENT=dev
        TF_VAR_environment=${{ inputs.environment }}
        echo "DEPLOY_ENV=review" >> $GITHUB_ENV
        pr_id=${{ inputs.pr_id }}
        echo "pr_id=${pr_id}" >> $GITHUB_ENV
        echo "PARAMETER_STORE_ENVIRONMENT=${PARAMETER_STORE_ENVIRONMENT}" >> $GITHUB_ENV
        echo "TF_VAR_environment=${TF_VAR_environment}" >> $GITHUB_ENV

    - name: Set environment variables for non-review environments
      if: startsWith(inputs.environment, 'review') != true
      shell: bash
      run: |
        PARAMETER_STORE_ENVIRONMENT=${{ inputs.environment }}
        DEPLOY_ENV=${{ inputs.environment }}
        echo "PARAMETER_STORE_ENVIRONMENT=${PARAMETER_STORE_ENVIRONMENT}" >> $GITHUB_ENV
        echo "DEPLOY_ENV=${DEPLOY_ENV}" >> $GITHUB_ENV
        CONFIRM_PRODUCTION=YES
        echo "CONFIRM_PRODUCTION=${CONFIRM_PRODUCTION}" >> $GITHUB_ENV

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Download fetch_config.rb
      shell: bash
      run: |
        echo "::group:: Download fetch_config.rb script"
        curl -s https://raw.githubusercontent.com/DFE-Digital/bat-platform-building-blocks/master/scripts/fetch_config/fetch_config.rb -o bin/fetch_config.rb
        chmod +x bin/fetch_config.rb
        echo "::endgroup::"

    # Validate secrets stored in parameter store to prevent terraform from exposing them in case of an issue
    - name: Validate secrets
      shell: bash
      run: |
        gem install aws-sdk-ssm --no-document
        bin/fetch_config.rb -s aws-ssm-parameter-path:/teaching-vacancies/${{ env.PARAMETER_STORE_ENVIRONMENT }}/app -d quiet \
          && echo Data in "/teaching-vacancies/${{ env.PARAMETER_STORE_ENVIRONMENT }}" looks valid

    - name: Deploy to environment
      id: deployment-conclusion
      shell: bash
      run: |
        make ${{ env.DEPLOY_ENV }} ci tag=${{ inputs.tag }} terraform-apply
