# TODO: Legacy subscription token encryption, remove when fully migrated to signed ID
SUBSCRIPTION_KEY_GENERATOR_SECRET = ENV.fetch("SUBSCRIPTION_KEY_GENERATOR_SECRET", "")
SUBSCRIPTION_KEY_GENERATOR_SALT = ENV.fetch("SUBSCRIPTION_KEY_GENERATOR_SECRET", "")
SUBSCRIPTION_KEY_GENERATOR_DIGEST_CLASS = OpenSSL::Digest::SHA1
