{
 "title": "Teaching vacancies production",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests{space=\"teaching-vacancies-production\", app=\"teaching-vacancies-production\"}[5m]))*60",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(requests{space=\"teaching-vacancies-production\", app=\"teaching-vacancies-production\", status_range=~\"0xx|4xx|5xx\"}[5m]))*60",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Web app CPU (avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cpu{app=\"teaching-vacancies-production\"})",
     "legendFormat": "avg_cpu"
    }
   ]
  },
  {
   "title": "Worker CPU usage (avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cpu{app=\"teaching-vacancies-worker-production\"})",
     "legendFormat": "avg_cpu"
    }
   ]
  },
  {
   "title": "Web app memory (max)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(memory_utilization{space=\"teaching-vacancies-production\", app=\"teaching-vacancies-production\"})",
     "legendFormat": "max_mem"
    }
   ]
  },
  {
   "title": "Worker memory (max)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(memory_utilization{space=\"teaching-vacancies-production\", app=\"teaching-vacancies-worker-production\"})",
     "legendFormat": "max_mem"
    }
   ]
  }
 ]
}