common_caps:
  "browserstack.debug": true
  "browserstack.local": true
  "project": "TeachingJobs"

browser_caps:
  -
    "browser": "chrome"
  -
    "browser": "firefox"
  -
    "browser": "safari"
  -
    "browser": "IE"
    "browser_version": "11.0"
    "enablePersistentHover": false
  -
    "browser": "edge"
    "enablePersistentHover": false