shared:
  whentoapplybespoke+PRIMARY:
    banner_image: "campaigns/primary_teacher.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - primary
    radius: 15
  mostvacanciesbespoke+PRIMARY:
    banner_image: "campaigns/primary_teacher.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - primary
    radius: 15
  mostvacanciesbespoke+SECONDARY:
    banner_image: "campaigns/secondary_teacher.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - secondary
    radius: 15
  whentoapplybespoke+SECONDARY:
    banner_image: "campaigns/secondary_teacher.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - secondary
    radius: 15
  ectrolesbespoke:
    banner_image: "campaigns/ect_teacher.jpg"
    ect_suitable: true
    teaching_job_roles:
      - teacher
    radius: 15
  mathsbespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Mathematics
    radius: 15
  geographybespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Geography
    radius: 15
  languagesbespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Languages
    radius: 15
  pebespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Physical education
    radius: 15
  primarybespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - primary
    radius: 15
  secondarybespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - secondary
    radius: 15
  physicsbespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Physics
    radius: 15
  historybespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - History
    radius: 15
  designandtechnologybespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Design and technology
    radius: 15
  sciencebespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Science
    radius: 15
  dancedramamusicbespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Dance
      - Drama
      - Music
    radius: 15
  computingbespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Computing
    radius: 15
  chemistrybespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Chemistry
    radius: 15
  businessandeconomicsbespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Business studies
      - Economics
    radius: 15
  re:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Religious education
    radius: 15
  biologybespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Biology
    radius: 15
  englishbespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - English
    radius: 15
  psychologybespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Psychology
    radius: 15
  artanddesignbespoke:
    banner_image: "campaigns/subjects.jpg"
    teaching_job_roles:
      - teacher
    subjects:
      - Art and design
    radius: 15
  parttimebespoke+PRIMARY:
    banner_image: "campaigns/primary_part_time.jpg"
    teaching_job_roles:
      - teacher
    working_patterns:
      - part_time
      - job_share
    radius: 15
  parttimebespoke+SECONDARY:
    banner_image: "campaigns/secondary_part_time.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - secondary
    working_patterns:
      - part_time
      - job_share
    radius: 15
  stilltimebespoke+PRIMARY:
    banner_image: "campaigns/primary_not_too_late.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - primary
    radius: 15
  stilltimebespoke+SECONDARY:
    banner_image: "campaigns/secondary_not_too_late.jpg"
    teaching_job_roles:
      - teacher
    phases:
      - secondary
    radius: 15

####################################################################################################
# The data below is only used in automated tests, make sure you add your campaign pages to the
# `shared` section above!
####################################################################################################
test:
  FAKE1+CAMPAIGN:
    banner_image: "campaigns/secondary_not_too_late.jpg"
    teaching_job_roles:
      - teacher
    working_patterns:
      - part_time
    subjects:
      - Physics
      - Science
    radius: 15
