test:
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  encoding: unicode
  database: <%= ENV["POSTGRES_DB"] %>
  pool: 20
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
