default: &default
  encoding: unicode
  # AKS DATABASE_URL will start with `postgres://`, which overrides the postgis adapter
  # so we need to replace `postgres` if it occurs at the beginning of DATABASE_URL
  url: <%= ENV.fetch('DATABASE_URL', 'postgis://postgres@localhost:5432').sub(/^postgres/, "postgis") %>
  pool: <%= Integer(ENV.fetch('RAILS_MAX_THREADS') { 5 }) %>

development:
  primary: &primary_development
    <<: *default
    adapter: postgis
    database: tvs_development
  queue:
    <<: *primary_development
    adapter: postgres
    database: tvs_development_queue
    migrations_paths: db/queue_migrate

test:
  primary: &primary_test
    <<: *default
    adapter: postgis
    database: tvs_test<%= ENV['TEST_ENV_NUMBER'] %>
  queue:
    <<: *primary_test
    adapter: postgres
    database: tvs_queue_test<%= ENV['TEST_ENV_NUMBER'] %>
    migrations_paths: db/queue_migrate

staging:
  primary: &primary_staging
    <<: *default
    adapter: postgis
  queue:
    <<: *primary_staging
    adapter: postgres
    database: tvs_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    adapter: postgis
  queue:
    <<: *primary_production
    adapter: postgres
    url: <%= ENV['DATABASE_QUEUE_URL'] %>
    migrations_paths: db/queue_migrate
