shared:
  ##
  # Configuration for "static" (non-location) landing pages
  #   Every key in this configuration file is a landing page slug that will be available on the
  #   app at a root URL level, and the data nested below is treated as a search criteria hash of
  #   the form you would pass into `VacancySearch`.
  #   Landing pages for locations are dynamic and not specified here, they are based on the
  #   `LocationPolygon`s in the database.
  #   Don't forget to restart your Rails server after modifying this file locally.
  #
  # IMPORTANT: Every landing page defined here also needs corresponding content to be added to the
  # translations file in `config/locales/landing_pages.yml`!
  # IMPORTANT: When removing landing pages or changing the slug, make sure you also remove/update
  # any links to them throughout the service, such as on the homepage!
  #
  # This file should ideally only be modified by developers (to ensure the format of the search
  # criteria is correct and doesn't break the search engine).

  ### Job roles
  sendco-jobs:
    teaching_job_roles:
      - sendco
  teacher-jobs:
    teaching_job_roles:
      - teacher
  headteacher-jobs:
    teaching_job_roles:
      - headteacher
  head-of-department-or-curriculum-jobs:
    teaching_job_roles:
      - head_of_department_or_curriculum
  head-of-year-or-phase-jobs:
    teaching_job_roles:
      - head_of_year_or_phase
  assistant-headteacher-jobs:
    teaching_job_roles:
      - assistant_headteacher
  deputy-headteacher-jobs:
    teaching_job_roles:
      - deputy_headteacher
  other-leadership-roles-jobs:
      teaching_job_roles:
        - other_leadership
  ect-suitable-jobs:
    ect_statuses:
      - ect_suitable
  education-support-jobs:
    support_job_roles:
      - education_support
  higher-level-teaching-assistant-jobs:
    support_job_roles:
      - higher_level_teaching_assistant
  teaching-assistant-jobs:
    support_job_roles:
      - teaching_assistant
  teaching-assistant-jobs-v2:
    banner_image: "landing_pages/teaching_support_banner.jpg"
    support_job_roles:
      - teaching_assistant
    hidden_filters:
      - visa_sponsorship
      - teaching_job_roles
      - subjects
      - ect_statuses
  administration-hr-data-finance-jobs:
    support_job_roles:
      - administration_hr_data_and_finance
  catering-cleaning-site-management-jobs:
    support_job_roles:
      - catering_cleaning_and_site_management
  it-support-jobs:
    support_job_roles:
      - it_support
  pastoral-health-welfare-jobs:
    support_job_roles:
      - pastoral_health_and_welfare
  other-support-roles-jobs:
    support_job_roles:
      - other_support
  support-jobs:
    support_job_roles:
      - teaching_assistant
      - higher_level_teaching_assistant
      - education_support
      - administration_hr_data_and_finance
      - catering_cleaning_and_site_management
      - it_support
      - pastoral_health_and_welfare
      - other_support

  ### FE Job roles
  fe-teacher-jobs:
    teaching_job_roles:
      - teacher
    phases:
      - sixth_form_or_college
  fe-headteacher-jobs:
    teaching_job_roles:
      - headteacher
    phases:
      - sixth_form_or_college
  fe-deputy-headteacher-jobs:
    teaching_job_roles:
      - deputy_headteacher
    phases:
      - sixth_form_or_college
  fe-assistant-headteacher-jobs:
    teaching_job_roles:
      - assistant_headteacher
    phases:
      - sixth_form_or_college
  fe-head-of-department-or-curriculum-jobs:
    teaching_job_roles:
      - head_of_department_or_curriculum
    phases:
      - sixth_form_or_college
  fe-head-of-year-or-phase-jobs:
    teaching_job_roles:
      - head_of_year_or_phase
    phases:
      - sixth_form_or_college
  fe-sendco-jobs:
    teaching_job_roles:
      - sendco
    phases:
      - sixth_form_or_college
  fe-other-leadership-roles-jobs:
    teaching_job_roles:
      - other_leadership
    phases:
      - sixth_form_or_college
  fe-teaching-assistant-jobs:
    support_job_roles:
      - teaching_assistant
    phases:
      - sixth_form_or_college
  fe-higher-level-teaching-assistant-jobs:
    support_job_roles:
      - higher_level_teaching_assistant
    phases:
      - sixth_form_or_college
  fe-education-support-jobs:
    support_job_roles:
      - education_support
    phases:
      - sixth_form_or_college
  fe-administration-hr-data-finance-jobs:
    support_job_roles:
      - administration_hr_data_and_finance
    phases:
      - sixth_form_or_college
  fe-catering-cleaning-site-management-jobs:
    support_job_roles:
      - catering_cleaning_and_site_management
    phases:
      - sixth_form_or_college
  fe-it-support-jobs:
    support_job_roles:
      - it_support
    phases:
      - sixth_form_or_college
  fe-pastoral-health-welfare-jobs:
    support_job_roles:
      - pastoral_health_and_welfare
    phases:
      - sixth_form_or_college
  fe-other-support-roles-jobs:
    support_job_roles:
      - other_support
    phases:
      - sixth_form_or_college

  ### Phases
  nursery-jobs:
    phases:
      - nursery
  primary-school-jobs:
    phases:
      - primary
  middle-school-jobs:
    phases:
      - primary
      - secondary
  secondary-school-jobs:
    phases:
      - secondary
  sixth-form-or-college-jobs:
    phases:
      - sixth_form_or_college
  through-school-jobs:
    phases:
      - through

  ### Subjects
  art-design-technology-teacher-jobs:
    subjects:
      - Art and design
      - Design and technology
  art-design-teacher-jobs:
    subjects:
      - Art and design
  design-technology-teacher-jobs:
    subjects:
      - Design and technology
  biology-teacher-jobs:
    subjects:
      - Biology
  chemistry-teacher-jobs:
    subjects:
      - Chemistry
  classics-latin-teacher-jobs:
    subjects:
      - Classics
  dance-drama-music-teacher-jobs:
    subjects:
      - Dance
      - Drama
      - Music
  economics-business-studies-teacher-jobs:
    subjects:
      - Economics
      - Business studies
  english-media-studies-teacher-jobs:
    subjects:
      - English
      - Media studies
  food-technology-teacher-jobs:
    subjects:
      - Food technology
  french-teacher-jobs:
    subjects:
      - French
  geography-teacher-jobs:
    subjects:
      - Geography
  german-teacher-jobs:
    subjects:
      - German
  health-relationships-social-care-teacher-jobs:
    subjects:
      - Health and social care
      - Relationships and sex education
  history-teacher-jobs:
    subjects:
      - History
  ict-computer-science-teacher-jobs:
    subjects:
      - ICT
      - Computing
  mandarin-teacher-jobs:
    subjects:
      - Mandarin
  maths-teacher-jobs:
    subjects:
      - Mathematics
  mfl-teacher-jobs:
    subjects:
      - Languages
      - French
      - Spanish
      - German
      - Mandarin
      - Classics
  physical-education-teacher-jobs:
    subjects:
      - Physical education
  physics-teacher-jobs:
    subjects:
      - Physics
  politics-humanities-social-sciences-teacher-jobs:
    subjects:
      - Politics
      - Humanities
      - Social sciences
  psychology-philosophy-sociology-re-teacher-jobs:
    subjects:
      - Psychology
      - Philosophy
      - Sociology
      - Religious education
  science-teacher-jobs:
    subjects:
      - Biology
      - Chemistry
      - Physics
      - Science
  spanish-teacher-jobs:
    subjects:
      - Spanish

  ### FE Subjects
  accountancy-and-finance-fe-jobs:
    subjects:
      - Accountancy and finance
    phases:
      - sixth_form_or_college
  agriculture-horticulture-land-based-studies-fe-jobs:
    subjects:
      - Agriculture/horticulture/land based studies
    phases:
      - sixth_form_or_college
  animal-care-fe-jobs:
    subjects:
      - Animal care
    phases:
      - sixth_form_or_college
  art-and-design-fe-jobs:
    subjects:
      - Art and design
    phases:
      - sixth_form_or_college
  biology-fe-jobs:
    subjects:
      - Biology
    phases:
      - sixth_form_or_college
  british-sign-language-fe-jobs:
    subjects:
      - British sign language
    phases:
      - sixth_form_or_college
  building-and-construction-fe-jobs:
    subjects:
      - Building and construction
    phases:
      - sixth_form_or_college
  catering-fe-jobs:
    subjects:
      - Catering
    phases:
      - sixth_form_or_college
  chemistry-fe-jobs:
    subjects:
      - Chemistry
    phases:
      - sixth_form_or_college
  childrens-development-and-learning-fe-jobs:
    subjects:
      - Children's development and learning
    phases:
      - sixth_form_or_college
  classics-fe-jobs:
    subjects:
      - Classics
    phases:
      - sixth_form_or_college
  computer-science-fe-jobs:
    subjects:
      - Computer science
    phases:
      - sixth_form_or_college
  construction-fe-jobs:
    subjects:
      - Construction
    phases:
      - sixth_form_or_college
  counselling-fe-jobs:
    subjects:
      - Counselling
    phases:
      - sixth_form_or_college
  customer-service-fe-jobs:
    subjects:
      - Customer service
    phases:
      - sixth_form_or_college
  dance-drama-and-music-fe-jobs:
    subjects:
      - Dance drama and music
    phases:
      - sixth_form_or_college
  design-and-technology-fe-jobs:
    subjects:
      - Design and technology
    phases:
      - sixth_form_or_college
  early-years-fe-jobs:
    subjects:
      - Early years
    phases:
      - sixth_form_or_college
  economics-and-business-studies-fe-jobs:
    subjects:
      - Economics and Business Studies
    phases:
      - sixth_form_or_college
  electrics-fe-jobs:
    subjects:
      - Electrics
    phases:
      - sixth_form_or_college
  engineering-fe-jobs:
    subjects:
      - Engineering
    phases:
      - sixth_form_or_college
  english-and-media-studies-fe-jobs:
    subjects:
      - English and Media Studies
    phases:
      - sixth_form_or_college
  english-as-a-foreign-language-fe-jobs:
    subjects:
      - English as a foreign language
    phases:
      - sixth_form_or_college
  fabrication-and-welding-fe-jobs:
    subjects:
      - Fabrication and welding
    phases:
      - sixth_form_or_college
  farming-fe-jobs:
    subjects:
      - Farming
    phases:
      - sixth_form_or_college
  fashion-fe-jobs:
    subjects:
      - Fashion
    phases:
      - sixth_form_or_college
  food-technology-fe-jobs:
    subjects:
      - Food technology
    phases:
      - sixth_form_or_college
  foreign-languages-fe-jobs:
    subjects:
      - Foreign languages
    phases:
      - sixth_form_or_college
  french-fe-jobs:
    subjects:
      - French
    phases:
      - sixth_form_or_college
  functional-skills-fe-jobs:
    subjects:
      - Functional skills
    phases:
      - sixth_form_or_college
  games-design-fe-jobs:
    subjects:
      - Games design
    phases:
      - sixth_form_or_college
  geography-fe-jobs:
    subjects:
      - Geography
    phases:
      - sixth_form_or_college
  german-fe-jobs:
    subjects:
      - German
    phases:
      - sixth_form_or_college
  graphic-design-fe-jobs:
    subjects:
      - Graphic design
    phases:
      - sixth_form_or_college
  hair-and-beauty-fe-jobs:
    subjects:
      - Hair and beauty
    phases:
      - sixth_form_or_college
  health-and-social-care-fe-jobs:
    subjects:
      - Health and Social Care
    phases:
      - sixth_form_or_college
  history-fe-jobs:
    subjects:
      - History
    phases:
      - sixth_form_or_college
  hotel-catering-and-travel-fe-jobs:
    subjects:
      - Hotel catering and travel
    phases:
      - sixth_form_or_college
  humanities-fe-jobs:
    subjects:
      - Humanities
    phases:
      - sixth_form_or_college
  ict-and-computer-science-fe-jobs:
    subjects:
      - ICT and Computer Science
    phases:
      - sixth_form_or_college
  land-and-property-management-fe-jobs:
    subjects:
      - Land and Property Management
    phases:
      - sixth_form_or_college
  leadership-and-management-fe-jobs:
    subjects:
      - Leadership and management
    phases:
      - sixth_form_or_college
  logistics-fe-jobs:
    subjects:
      - Logistics
    phases:
      - sixth_form_or_college
  mandarin-fe-jobs:
    subjects:
      - Mandarin
    phases:
      - sixth_form_or_college
  maths-fe-jobs:
    subjects:
      - Maths
    phases:
      - sixth_form_or_college
  modern-foreign-languages-fe-jobs:
    subjects:
      - Modern foreign languages
    phases:
      - sixth_form_or_college
  motor-vehicle-fe-jobs:
    subjects:
      - Motor vehicle
    phases:
      - sixth_form_or_college
  music-fe-jobs:
    subjects:
      - Music
    phases:
      - sixth_form_or_college
  people-management-fe-jobs:
    subjects:
      - People management
    phases:
      - sixth_form_or_college
  philosophy-fe-jobs:
    subjects:
      - Philosophy
    phases:
      - sixth_form_or_college
  photography-fe-jobs:
    subjects:
      - Photography
    phases:
      - sixth_form_or_college
  physical-education-fe-jobs:
    subjects:
      - Physical Education
    phases:
      - sixth_form_or_college
  physics-fe-jobs:
    subjects:
      - Physics
    phases:
      - sixth_form_or_college
  plumbing-and-heating-fe-jobs:
    subjects:
      - Plumbing and heating
    phases:
      - sixth_form_or_college
  politics-fe-jobs:
    subjects:
      - Politics
    phases:
      - sixth_form_or_college
  pshe-fe-jobs:
    subjects:
      - PSHE
    phases:
      - sixth_form_or_college
  psychology-fe-jobs:
    subjects:
      - Psychology
    phases:
      - sixth_form_or_college
  public-services-fe-jobs:
    subjects:
      - Public services
    phases:
      - sixth_form_or_college
  religious-education-fe-jobs:
    subjects:
      - Religious education
    phases:
      - sixth_form_or_college
  science-fe-jobs:
    subjects:
      - Science
    phases:
      - sixth_form_or_college
  send-fe-jobs:
    subjects:
      - SEND
    phases:
      - sixth_form_or_college
  sociology-fe-jobs:
    subjects:
      - Sociology
    phases:
      - sixth_form_or_college
  spanish-fe-jobs:
    subjects:
      - Spanish
    phases:
      - sixth_form_or_college
  sport-and-leisure-fe-jobs:
    subjects:
      - Sport and leisure
    phases:
      - sixth_form_or_college
  sports-science-fe-jobs:
    subjects:
      - Sports science
    phases:
      - sixth_form_or_college
  tourism-fe-jobs:
    subjects:
      - Tourism
    phases:
      - sixth_form_or_college
  welsh-fe-jobs:
    subjects:
      - Welsh
    phases:
      - sixth_form_or_college
  woodworking-joinery-and-carpentry-fe-jobs:
    subjects:
      - Woodworking joinery and carpentry
    phases:
      - sixth_form_or_college

  ### Working patterns
  full-time-school-jobs:
    working_patterns:
      - full_time
  part-time-school-jobs:
    working_patterns:
      - part_time
  school-job-shares:
    working_patterns:
      - job_share
  school-term-time-jobs:
    working_patterns:
      - part_time
  flexible-working-jobs-in-schools:
    working_patterns:
      - part_time

####################################################################################################
# The data below is only used in automated tests, make sure you add your landing pages to the
# `shared` section above!
####################################################################################################
test:
  part-time-potions-and-sorcery-teacher-jobs:
    banner_image: "landing_pages/teaching_support_banner.jpg"
    working_patterns:
      - part_time
    subjects:
      - Potions
      - Sorcery
