aggregate_vacancy_referrer_stats:
  schedule: "*/15 * * * *" # Every 15 minutes
  class: 'AggregateVacancyReferrerStatsJob'
  queue: low

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
