require "rails_helper"

RSpec.describe "Creating a vacancy" do
  let(:publisher) { create(:publisher) }
  let!(:publisher_preference) { create(:publisher_preference, publisher: publisher, organisation: school_group, schools: [school1, school2]) }
  let(:school_group) { create(:local_authority, schools: [school1, school2]) }
  let(:school1) { create(:school, phase: :not_applicable, name: "First school") }
  let(:school2) { create(:school, phase: :not_applicable, name: "Second school") }
  let(:vacancy) do
    build(:vacancy, :no_tv_applications, :secondary, :fixed_term, :ect_suitable, job_roles: ["teacher"],
                                                                                 working_patterns: %w[full_time part_time], hourly_rate: nil,
                                                                                 organisations: [school1, school2],
                                                                                 contact_email: publisher.email,
                                                                                 publisher: publisher)
  end
  let(:created_vacancy) { DraftVacancy.last }

  # searchable_content is autogenerated and its string representation is non-deterministic
  let(:ignored_fields) { %i[searchable_content id updated_at created_at geolocation slug completed_steps publisher_id publisher_organisation_id] }

  before do
    login_publisher(publisher: publisher, organisation: school_group)
  end

  after { logout }

  scenario "publishes a vacancy" do
    visit organisation_jobs_with_type_path
    click_on I18n.t("buttons.create_job")
    expect(current_path).to eq(organisation_jobs_start_path)
    click_on I18n.t("buttons.create_job")

    expect(publisher_job_location_page).to be_displayed
    click_on I18n.t("buttons.continue")
    expect(publisher_job_location_page).to be_displayed
    expect(publisher_job_location_page.errors.map(&:text)).to eq([I18n.t("job_location_errors.organisation_ids.blank")])
    publisher_job_location_page.fill_in_and_submit_form(vacancy)

    expect(publisher_job_title_page).to be_displayed
    submit_empty_form
    expect(publisher_job_title_page).to be_displayed
    expect(publisher_job_title_page.errors.map(&:text)).to contain_exactly(I18n.t("job_title_errors.job_title.blank"))
    publisher_job_title_page.fill_in_and_submit_form(vacancy.job_title)

    expect(publisher_job_role_page).to be_displayed
    submit_empty_form
    expect(publisher_job_role_page).to be_displayed
    expect(publisher_job_role_page.errors.map(&:text)).to contain_exactly(I18n.t("job_roles_errors.job_roles.blank"))
    publisher_job_role_page.fill_in_and_submit_form(vacancy.job_roles.first)

    expect(publisher_education_phase_page).to be_displayed
    submit_empty_form
    expect(publisher_education_phase_page).to be_displayed
    expect(publisher_education_phase_page.errors.map(&:text)).to contain_exactly(I18n.t("education_phases_errors.phases.blank"))
    publisher_education_phase_page.fill_in_and_submit_form(vacancy.phases.first)

    expect(publisher_key_stage_page).to be_displayed
    submit_empty_form
    expect(publisher_key_stage_page).to be_displayed
    expect(publisher_key_stage_page.errors.map(&:text)).to contain_exactly(I18n.t("key_stages_errors.key_stages.blank"))
    publisher_key_stage_page.fill_in_and_submit_form(vacancy.key_stages)

    expect(publisher_subjects_page).to be_displayed
    publisher_subjects_page.fill_in_and_submit_form(vacancy.subjects)

    expect(publisher_contract_information_page).to be_displayed
    submit_empty_form
    expect(publisher_contract_information_page).to be_displayed
    expect(publisher_contract_information_page.errors.map(&:text)).to contain_exactly(
      I18n.t("contract_information_errors.contract_type.inclusion"),
      I18n.t("contract_information_errors.working_patterns.inclusion"),
      I18n.t("contract_information_errors.is_job_share.inclusion"),
    )
    publisher_contract_information_page.fill_in_and_submit_form(vacancy, contract_length: "6 months")

    expect(publisher_start_date_page).to be_displayed
    submit_empty_form
    expect(publisher_start_date_page).to be_displayed
    expect(publisher_start_date_page.errors.map(&:text)).to contain_exactly(I18n.t("start_date_errors.start_date_type.inclusion"))
    publisher_start_date_page.fill_in_and_submit_form(vacancy.starts_on)

    expect(publisher_pay_package_page).to be_displayed
    submit_empty_form
    expect(publisher_pay_package_page).to be_displayed
    expect(publisher_pay_package_page.errors.map(&:text)).to contain_exactly(
      I18n.t("pay_package_errors.salary_types.invalid"),
      I18n.t("pay_package_errors.benefits.inclusion"),
    )
    expect_correct_pay_package_options(vacancy)
    publisher_pay_package_page.fill_in_and_submit_form(vacancy)

    expect(publisher_about_the_role_page).to be_displayed
    submit_empty_form
    expect(publisher_about_the_role_page).to be_displayed
    expect(publisher_about_the_role_page.errors.map(&:text)).to contain_exactly(
      I18n.t("about_the_role_errors.ect_status.inclusion"),
      I18n.t("about_the_role_errors.skills_and_experience.blank"),
      I18n.t("about_the_role_errors.further_details_provided.inclusion"),
      I18n.t("about_the_role_errors.school_offer.blank", organisation: "schools"),
      I18n.t("about_the_role_errors.flexi_working_details_provided.inclusion"),
    )
    publisher_about_the_role_page.fill_in_and_submit_form(vacancy)

    expect(publisher_include_additional_documents_page).to be_displayed
    submit_empty_form
    expect(page).to have_content("There is a problem")
    expect(publisher_include_additional_documents_page.errors.map(&:text)).to contain_exactly(I18n.t("include_additional_documents_errors.include_additional_documents.inclusion"))
    publisher_include_additional_documents_page.fill_in_and_submit_form(vacancy.include_additional_documents)

    expect(publisher_school_visits_page).to be_displayed
    submit_empty_form
    expect(publisher_school_visits_page).to be_displayed
    expect(publisher_school_visits_page.errors.map(&:text)).to contain_exactly(I18n.t("school_visits_errors.school_visits.inclusion"))
    publisher_school_visits_page.fill_in_and_submit_form(vacancy.school_visits)

    expect(publisher_visa_sponsorship_page).to be_displayed
    submit_empty_form
    expect(publisher_visa_sponsorship_page.errors.map(&:text)).to contain_exactly(I18n.t("visa_sponsorship_available_errors.visa_sponsorship_available.inclusion"))
    expect(publisher_visa_sponsorship_page).to be_displayed
    publisher_visa_sponsorship_page.fill_in_and_submit_form(vacancy.visa_sponsorship_available)

    expect(publisher_important_dates_page).to be_displayed
    submit_empty_form
    expect(publisher_important_dates_page).to be_displayed
    expect(publisher_important_dates_page.errors.map(&:text)).to contain_exactly(
      I18n.t("important_dates_errors.publish_on_day.inclusion"),
      I18n.t("important_dates_errors.expires_at.blank"),
      I18n.t("important_dates_errors.expiry_time.inclusion"),
    )
    publisher_important_dates_page.fill_in_and_submit_form(publish_on: vacancy.publish_on, expires_at: vacancy.expires_at)

    expect(publisher_applying_for_the_job_page).to be_displayed
    submit_empty_form
    expect(publisher_applying_for_the_job_page).to be_displayed
    expect(publisher_applying_for_the_job_page.errors.map(&:text)).to contain_exactly(I18n.t("applying_for_the_job_errors.application_form_type.blank"))
    publisher_applying_for_the_job_page.fill_in_and_submit_form

    expect(publisher_how_to_receive_applications_page).to be_displayed
    submit_empty_form
    expect(publisher_how_to_receive_applications_page).to be_displayed
    expect(publisher_how_to_receive_applications_page.errors.map(&:text)).to contain_exactly(I18n.t("how_to_receive_applications_errors.receive_applications.inclusion"))
    publisher_how_to_receive_applications_page.fill_in_and_submit_form(vacancy)

    expect(publisher_application_link_page).to be_displayed
    submit_empty_form
    expect(publisher_application_link_page.errors.map(&:text)).to contain_exactly(I18n.t("application_link_errors.application_link.blank"))
    expect(publisher_application_link_page).to be_displayed
    publisher_application_link_page.fill_in_and_submit_form(vacancy.application_link)

    expect(publisher_contact_details_page).to be_displayed
    submit_empty_form
    expect(publisher_contact_details_page.errors.map(&:text)).to contain_exactly(
      I18n.t("contact_details_errors.contact_email.blank"),
      I18n.t("contact_details_errors.contact_number_provided.inclusion"),
    )
    expect(publisher_contact_details_page).to be_displayed
    non_publisher_email = Faker::Internet.email(domain: "contoso.com")
    publisher_contact_details_page.fill_in_and_submit_form(non_publisher_email, vacancy.contact_number)

    expect(publisher_confirm_contact_details_page).to be_displayed

    publisher_confirm_contact_details_page.click_change_email_button

    expect(publisher_contact_details_page).to be_displayed

    publisher_contact_details_page.fill_in_and_submit_form(publisher.email, vacancy.contact_number, other: false)

    expect(current_path).to eq(organisation_job_review_path(created_vacancy.id))
    # invitation email should not be sent as publisher is already registered on our service
    expect {
      click_on I18n.t("publishers.vacancies.show.heading_component.action.publish")
    }.not_to(change { ActionMailer::Base.deliveries.count })

    expect(current_path).to eq(organisation_job_summary_path(created_vacancy.id))

    expect(PublishedVacancy.find(created_vacancy.id).attributes.symbolize_keys.except(*ignored_fields))
      .to eq(vacancy.attributes.symbolize_keys.except(*ignored_fields))
  end

  def submit_empty_form
    click_on I18n.t("buttons.save_and_continue")
  end
end
