require "rails_helper"

RSpec.describe CopyVacancy do
  describe "#call" do
    let(:school) { create(:school) }

    it "creates a new vacancy as draft" do
      vacancy = create(:vacancy, organisations: [school], job_title: "Maths teacher")

      result = described_class.new(vacancy).call

      expect(result).to be_a(Vacancy)
      expect(Vacancy.count).to eq(2)
      expect(result.status).to eq("draft")
      expect(result.organisations).to eq [school]
    end

    it "does not change the original vacancy" do
      # Needed to compare a FactoryBot object fields for updated_at and created_at
      # and against the record it creates in Postgres.
      travel_to(Time.zone.local(2008, 9, 1, 12, 0, 0)) do
        vacancy = create(:vacancy, job_title: "Maths teacher", organisations: [school])

        described_class.new(vacancy).call

        # searchable_content is autogenerated and its string representation is non-deterministic
        expect(vacancy.attributes.except("searchable_content"))
          .to eq(Vacancy.find(vacancy.id).attributes.except("searchable_content"))
      end
    end

    context "when there are supporting documents" do
      let(:vacancy) { create(:vacancy, :with_supporting_documents, organisations: [school]) }
      let(:supporting_documents) { vacancy.supporting_documents.attachments }

      it "copies supporting_documents" do
        copied_vacancy = described_class.new(vacancy).call

        expect(copied_vacancy.supporting_documents.attachments.map(&:blob_id)).to eq(supporting_documents.map(&:blob_id))
      end

      it "sets include_additional_documents" do
        copied_vacancy = described_class.new(vacancy).call

        expect(copied_vacancy.include_additional_documents).to be true
      end
    end

    context "when an application form has been attached" do
      let(:vacancy) { create(:vacancy, :with_application_form, organisations: [school]) }
      let(:application_form) { vacancy.application_form.attachments }

      it "copies the application form" do
        copied_vacancy = described_class.new(vacancy).call

        expect(copied_vacancy.application_form.attachments.map(&:blob_id)).to eq(application_form.map(&:blob_id))
      end
    end

    context "not all fields are copied" do
      let(:vacancy) do
        create(:vacancy,
               job_title: "Maths teacher",
               slug: "maths-teacher",
               organisations: [school])
      end
      let(:result) { described_class.new(vacancy).call }

      it "does not copy the slug of a vacancy" do
        expect(Vacancy.find(result.id).slug).not_to eq("maths-teacher")
      end
    end
  end
end
