# Builds the manifest that describes the Publisher ATS API to the DfE "Find and Use an API"
# catalogue, with the deployed OpenAPI document embedded in it.
#
# The document is generated by `rake rswag:specs:swaggerize` in CI and baked into the image, so
# reading it here guarantees the catalogue describes what is actually deployed.
module FindAndUseAnApi
  class BuildManifest
    class Error < StandardError; end

    # We publish a single version of the ATS API. If a v2 is ever added this needs to grow into
    # one manifest per major version, as the catalogue keys entries on name + majorVersion.
    VERSION = "v1".freeze
    SPEC_FILENAME = "swagger.yaml".freeze

    METADATA = {
      name: "teaching-vacancies-ats-api",
      displayName: "Teaching Vacancies ATS API",
      description: "Lets applicant tracking systems and HR software manage job listings on " \
                   "Teaching Vacancies on behalf of schools, trusts and colleges in England.",
      overview: "The Teaching Vacancies ATS API lets an applicant tracking system create, " \
                "update, list and delete job listings for the schools and trusts it acts for. " \
                "Listings published through it appear on the Teaching Vacancies service, where " \
                "people looking for school jobs can search for them and subscribe to alerts.\r\n" \
                "\r\n" \
                "Access is by API key, issued as part of onboarding. To start an integration, " \
                "email teachingvacancies.ats@education.gov.uk.",
      siteUrl: "https://teaching-vacancies.service.gov.uk",
      backendType: "http",
      majorVersion: VERSION,
      visibility: "Public",
      tags: "teaching-vacancies;ats;vacancies;recruitment;schools",
      classification: "Public facing",
      serviceLevel: "24/7",
      technology: "REST, Ruby on Rails",
      usage: "Applicant tracking system and HR software vendors acting for schools and trusts",
    }.freeze

    ENVIRONMENTS = [
      { name: "staging", backendUrl: "https://staging.teaching-vacancies.service.gov.uk", visibility: "Public", enabled: true, backendMode: "None" },
      { name: "production", backendUrl: "https://teaching-vacancies.service.gov.uk", visibility: "Public", enabled: true, backendMode: "None" },
    ].freeze

    class << self
      def call
        METADATA.merge(
          environments: ENVIRONMENTS,
          releases: releases,
          schema: schema,
        )
      end

      private

      def releases
        [{
          isCurrent: true,
          name: VERSION,
          tag: "Live",
          notes: "Live release of the Teaching Vacancies ATS API.",
        }]
      end

      def schema
        {
          fileName: SPEC_FILENAME,
          name: VERSION,
          schemaType: "openapi",
          contentType: "application/yaml",
          documentContentValue: Base64.strict_encode64(spec_bytes),
        }
      end

      def spec_bytes
        raise Error, "No OpenAPI document at #{spec_path}" unless File.exist?(spec_path)

        File.binread(spec_path)
      end

      # `Rswag::Api.config.openapi_root` is the same directory rswag generates into and serves
      # `/ats-api-docs` from, so the catalogue and the published docs can never disagree.
      def spec_path
        File.join(Rswag::Api.config.openapi_root, VERSION, SPEC_FILENAME)
      end
    end
  end
end
