rule_files:
    - alert.rules.yml

evaluation_interval: 1m

tests:
    - name: Test ProdRequestsFailuresElevated alert
      interval: 1m
      # Series data.
      input_series:
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="0",organisation="dfe",space="teaching-vacancies-production",status_range="0xx"}'
            values: '0+0x4 0+10x4 50+50x4 300+100x4 800+200x4 1800'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="0",organisation="dfe",space="teaching-vacancies-production",status_range="2xx"}'
            values: '0+1000x4 0+1000x4 500+1000x4 1000+1000x4 6000+1000x4'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="0",organisation="dfe",space="teaching-vacancies-production",status_range="3xx"}'
            values: '0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="0",organisation="dfe",space="teaching-vacancies-production",status_range="4xx"}'
            values: '0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="0",organisation="dfe",space="teaching-vacancies-production",status_range="5xx"}'
            values: '0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="1",organisation="dfe",space="teaching-vacancies-production",status_range="0xx"}'
            values: '0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="1",organisation="dfe",space="teaching-vacancies-production",status_range="2xx"}'
            values: '0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="1",organisation="dfe",space="teaching-vacancies-production",status_range="3xx"}'
            values: '0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="1",organisation="dfe",space="teaching-vacancies-production",status_range="4xx"}'
            values: '0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4'
          - series: 'requests{app="teaching-vacancies-production",guid="c95fd761-9b05-4527-829b-fd691a6c755a",instance="1",organisation="dfe",space="teaching-vacancies-production",status_range="5xx"}'
            values: '0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4 0+0x4'



      # Unit test for alerting rules.
      alert_rule_test:
          - alertname: ProdRequestsFailuresElevated
            eval_time: 5m # Only 200 requests - 1000 per minute
          - alertname: ProdRequestsFailuresElevated
            eval_time: 10m # 10 failed requests per minute (0.99% total)
          - alertname: ProdRequestsFailuresElevated
            eval_time: 15m # 50 failed requests per minute (4.76% total)
          - alertname: ProdRequestsFailuresElevated
            eval_time: 20m # 100 failed requests per minute (9.09% total)
          - alertname: ProdRequestsFailuresElevated
            eval_time: 25m # 200 failed requests per minute (16.67% total)
            exp_alerts:
            - exp_annotations:
                summary: High rate of failing requests
                description: "The proportion of failed HTTP requests in the past 5 min is above 10% (current value: 16.67%)"
                runbook: https://github.com/DFE-Digital/teaching-vacancies/tree/master/documentation/alert-runbook.md#ProdRequestsFailuresElevated
                dashboard: https://grafana-teaching-vacancies.london.cloudapps.digital/d/6Ac4lUWGk/teaching-vacancies-production?orgId=1&refresh=5s
              exp_labels:
                environment: production
                severity: high

    - name: Test ProdSlowRequests alert
      interval: 1m
      # Series data.
      input_series:
          - series: 'response_time_bucket{app="teaching-vacancies-production",status_range="2xx",le="1" }'
            values: '0 0 0 0 0 0 10 20 30 40 50 50 50 50 50 50'
          - series: 'response_time_bucket{app="teaching-vacancies-production",status_range="2xx",le="5" }'
            values: '0 0 0 0 0 0 10 20 30 40 50 60 70 80 90 100'
          - series: 'response_time_bucket{app="teaching-vacancies-production",status_range="2xx",le="10" }'
            values: '0 0 0 0 0 0 10 20 30 40 50 60 70 80 90 100'
          - series: 'response_time_bucket{app="teaching-vacancies-production", status_range="2xx",le="+Inf"}'
            values: '0 0 0 0 0 0 10 20 30 40 50 60 70 80 90 100'

      # Unit test for alerting rules.
      alert_rule_test:
          - alertname: ProdSlowRequests
            eval_time: 5m # No request no alert

          - alertname: ProdSlowRequests
            eval_time: 10m # Fast requests (10 request per minute under 1s response time ) no alert

          - alertname: ProdSlowRequests
            eval_time: 15m # Slow requests (10 request per minute between 1s and 5s response time) with triggered alert
            exp_alerts:
            - exp_annotations:
                summary: Identify slow running request above 95 percentile
                description: "Identify slow running http request above 95 percentile above 3sec (current value: 4.6s )"
                runbook: https://github.com/DFE-Digital/teaching-vacancies/tree/master/documentation/alert-runbook.md#ProdSlowRequests
                dashboard: https://grafana-teaching-vacancies.london.cloudapps.digital/d/6Ac4lUWGk/teaching-vacancies-production?orgId=1&refresh=5s
                # Labels - additional labels to be attached to the alert
              exp_labels:
                  environment: production
                  severity: high
