module Subjects
  SUBJECT_OPTIONS = [
    ['All or Not applicable', 'applies to examples such as primary school roles'],
    ['Accounting', 'includes Finance and accounting'],
    ['Art and design', ''],
    ['Bengali', ''],
    ['Biology', ''],
    ['Business studies', ''],
    ['Chemistry', ''],
    ['Citizenship', ''],
    ['Classics', 'includes Latin'],
    ['Computing', 'includes Computer science, Information technology, and ICT'],
    ['Dance', ''],
    ['Design and technology', 'includes Product design, Textiles and Systems and control'],
    ['Drama', 'includes Theatre studies and Performing arts'],
    ['Early years', 'includes EYFS'],
    ['Economics', ''],
    ['Engineering', ''],
    ['English', 'includes English language and literature'],
    ['Food', 'includes Hospitality and catering'],
    ['French', ''],
    ['Geography', ''],
    ['German', ''],
    ['Health and social care', ''],
    ['History', ''],
    ['Humanities', ''],
    ['ICT', ''],
    ['Italian', ''],
    ['Japanese', ''],
    ['Languages', 'includes MFL (Modern Foreign Languages)'],
    ['Law', ''],
    ['Mandarin', ''],
    ['Mathematics', ''],
    ['Media studies', ''],
    ['Music', ''],
    ['Philosophy', ''],
    ['Physical education', ''],
    ['Physics', ''],
    ['Politics', ''],
    ['Primary', ''],
    ['Psychology', ''],
    ['Relationships and sex education', ''],
    ['Religious education', 'includes Religious studies'],
    ['Russian', ''],
    ['Science', ''],
    ['Social sciences', ''],
    ['Sociology', ''],
    ['Spanish', ''],
    ['Statistics', '']
  ]
end
