name: Build and deploy - 2847

on:
  push:
    branches:
    - 2846-monitoring-resources-iac
    paths-ignore:
    - 'bigquery/**'
    - 'documentation/**'
    - 'terraform/common/**'
    - 'spec/fixtures/files/*.md'
    - 'app/mailers/previewing_emails.md'
    - 'README.md'
    - 'app/assets/stylesheets/README.md'
    - '.github/pull_request_template.md'

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
        - qa
        - staging
        - production

concurrency: workflow-Build-and-deploy-${{ github.ref }}
permissions:
  id-token: write
  packages: write
  pull-requests: write

jobs:
  deploy:
    name: Deploy app
    environment: ${{ matrix.environment }}
    strategy:
      max-parallel: 1
      matrix: 
        environment: [qa, production]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1
      name: Checkout Code

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6.2.3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
        role-to-assume: Deployments
        role-duration-seconds: 3600
        role-skip-session-tagging: true

    - name: Set environment variable (Push)
      if: github.event_name == 'push'
      run: |
        ENVIRONMENT=${{ matrix.environment }}
        echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV

    - name: Deploy App to ${{ env.ENVIRONMENT }} environment
      id: deploy_app_to_env
      uses: ./.github/actions/deploy_2847/
      with:
        environment: ${{ env.ENVIRONMENT }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        action_group_email_receivers: ${{ secrets.ACTION_GROUP_EMAIL_RECEIVERS }}
        action_group_sms_receivers: ${{ secrets.ACTION_GROUP_SMS_RECEIVERS }}
