# Workflow to integrate third-party code scanning tools with GitHub Security code scanning.

# This workflow integrates Brakeman with GitHub's Code Scanning feature
# Brakeman is a static analysis security vulnerability scanner for Ruby on Rails applications

name: GitHub Code Scanning third party tools

on:
  workflow_dispatch: # Manual trigger
  merge_group:
    branches: ['main']
  push:
    branches: ['main']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']
  schedule:
    - cron: '35 18 * * 0' #  Runs at 18:35, only on Sunday

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read

jobs:
  google-osv-scan-scheduled:
    name: Google OSV Scan - Full
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.8
    with:
      upload-sarif: false
      scan-args: |-
        --recursive
        $GITHUB_WORKSPACE

  google-osv-scan-pr:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Install OSV Scanner
        env:
          GOPATH: ${{ runner.temp }}
        run: go install github.com/google/osv-scanner/v2/cmd/osv-scanner@latest
        shell: bash

      - name: Run OSV Scanner
        run: ${{ runner.temp }}/bin/osv-scanner scan source --recursive ./
        shell: bash
