name: PR

on:
  pull_request:
    branches: [ master ]
    types: [assigned, opened, synchronize, reopened, closed]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install cloud foundry provider for terraform
      run: |
        set -eux
        TF_PLUGINS_DIR=$HOME/.terraform.d/plugins/linux_amd64
        mkdir -p $TF_PLUGINS_DIR
        wget -O $TF_PLUGINS_DIR/terraform-provider-cloudfoundry https://github.com/cloudfoundry-community/terraform-provider-cf/releases/download/v0.12.2/terraform-provider-cloudfoundry_linux_amd64
        chmod +x $TF_PLUGINS_DIR/terraform-provider-cloudfoundry
        ls -l $TF_PLUGINS_DIR
    
    - name: prepare env variables
      run: |
        set -eux
        echo "::set-env name=tf_workspace_name::$TF_WORKSPACE_NAME"
        echo "::set-env name=web_app_name::teaching-vacancies-pr-$TF_WORKSPACE_NAME"
        echo "::set-env name=postgres_service_name::teaching-postgres-vacancies-pr-$TF_WORKSPACE_NAME"
        echo "::set-env name=redis_service_name::teaching-vacancies-redis-pr-$TF_WORKSPACE_NAME"
        echo "::set-env name=papertrail_service_name::teaching-vacancies-papertrail-pr-$TF_WORKSPACE_NAME"
      env:
        TF_WORKSPACE_NAME: ${{ format('pr-{0}', github.event.number) }}

    - name: display env variables
      run: |
        set -eux
        echo $tf_workspace_name
        echo $web_app_name
        echo $postgres_service_name
        echo $redis_service_name
        echo $papertrail_service_name
        echo $TF_POSTGRES_SERVICE_NAME
      env:
        TF_WORKSPACE_NAME: ${{ format('pr-{0}', github.event.number) }}
        TF_POSTGRES_SERVICE_NAME: ${{ env.postgres_service_name }}

    - name: terraform workspace init
      run: |
        pwd && terraform init
        terraform workspace select $TF_WORKSPACE_NAME || terraform workspace new $TF_WORKSPACE_NAME
      working-directory: ./terraform/paas
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_WORKSPACE_NAME: ${{ format('pr-{0}', github.event.number) }}

    - name: terraform plan & apply
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      working-directory: ./terraform/paas
      run: |
        terraform plan -out tfplan
        terraform apply -auto-approve "tfplan"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_cf_user: ${{ secrets.CF_USERNAME }}
        TF_VAR_cf_password: ${{ secrets.CF_PASSWORD }}
        TF_VAR_cf_space_name: 'teaching-vacancies-review'
        TF_VAR_app_docker_image: 'dfedigital/teaching-vacancies:59fdf784712e8312fc7db42b5ef29e46454356d7'
        TF_VAR_app_stopped : true
        ## TODO append PR number to all these names
        TF_VAR_web_app_name: 'teaching-vacancies-review'
        TF_VAR_worker_app_name: 'teaching-vacancies-worker-review'
        TF_VAR_postgres_service_name: 'teaching-vacancies-postgres-review'
        TF_VAR_redis_service_name: 'teaching-vacancies-redis-review'
        TF_VAR_papertrail_service_name: 'teaching-vacancies-papertrail-review'
    
    - name: terraform destory (on PR closed)
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      working-directory: ./terraform/paas
      run: |
        terraform plan -destory -out tfdestroy
        terraform apply -auto-approve "tfdestroy"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_cf_user: ${{ secrets.CF_USERNAME }}
        TF_VAR_cf_password: ${{ secrets.CF_PASSWORD }}
        TF_VAR_cf_space_name: 'teaching-vacancies-review'
        TF_VAR_app_docker_image: 'dfedigital/teaching-vacancies:59fdf784712e8312fc7db42b5ef29e46454356d7'
        TF_VAR_app_stopped : true
        ## TODO append PR number to all these names
        TF_VAR_web_app_name: 'teaching-vacancies-review'
        TF_VAR_worker_app_name: 'teaching-vacancies-worker-review'
        TF_VAR_postgres_service_name: 'teaching-vacancies-postgres-review'
        TF_VAR_redis_service_name: 'teaching-vacancies-redis-review'
        TF_VAR_papertrail_service_name: 'teaching-vacancies-papertrail-review'
    
