name: PR

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, closed]

env:
  DOCKERHUB_REPOSITORY: dfedigital/teaching-vacancies
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      name: Checkout Code

    - name: build and push docker image
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.DOCKERHUB_REPOSITORY }}
        tags: ${{ github.sha }}
        target: production
        cache_froms: ${{ format('{0}:{1}', env.DOCKERHUB_REPOSITORY, github.sha) }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install cloud foundry provider for terraform
      run: |
        set -eux
        TF_PLUGINS_DIR=$HOME/.terraform.d/plugins/linux_amd64
        mkdir -p $TF_PLUGINS_DIR
        wget -O $TF_PLUGINS_DIR/terraform-provider-cloudfoundry https://github.com/cloudfoundry-community/terraform-provider-cf/releases/download/v0.12.2/terraform-provider-cloudfoundry_linux_amd64
        chmod +x $TF_PLUGINS_DIR/terraform-provider-cloudfoundry
        ls -l $TF_PLUGINS_DIR
    
    - name: prepare env variables
      run: |
        set -eux
        echo $GITHUB_EVENT_ACTION
        echo "::set-env name=TF_WORKSPACE_NAME::$TF_WORKSPACE_NAME"
        echo "::set-env name=TF_VAR_web_app_name::teaching-vacancies-$TF_WORKSPACE_NAME"
        echo "::set-env name=TF_VAR_worker_app_name::teaching-vacancies-worker-$TF_WORKSPACE_NAME"
        echo "::set-env name=TF_VAR_postgres_service_name::teaching-vacancies-postgres-$TF_WORKSPACE_NAME"
        echo "::set-env name=TF_VAR_redis_service_name::teaching-vacancies-redis-$TF_WORKSPACE_NAME"
        echo "::set-env name=TF_VAR_papertrail_service_name::teaching-vacancies-papertrail-$TF_WORKSPACE_NAME"
      env:
        TF_WORKSPACE_NAME: ${{ format('pr-{0}', github.event.number) }}
        GITHUB_EVENT_ACTION: ${{ github.event.action }}

    - name: terraform workspace init
      run: |
        set -eux
        pwd && terraform init -backend-config="workspace_key_prefix=env/review"
        terraform workspace select $TF_WORKSPACE_NAME || terraform workspace new $TF_WORKSPACE_NAME
      working-directory: ./terraform/paas
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: terraform plan & apply
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      working-directory: ./terraform/paas
      run: |
        terraform plan -out tfplan
        terraform apply -auto-approve "tfplan"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_cf_user: ${{ secrets.CF_USERNAME }}
        TF_VAR_cf_password: ${{ secrets.CF_PASSWORD }}
        TF_VAR_cf_space_name: 'teaching-vacancies-review'
        TF_VAR_app_docker_image: ${{ format('{0}:{1}', env.DOCKERHUB_REPOSITORY, github.sha) }}
        TF_VAR_app_stopped : true
        TF_VAR_papertrail_url: ${{ secrets.PAPERTRAIL_URL_DEV }}
    
    - name: terraform destroy (on PR closed)
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      working-directory: ./terraform/paas
      run: |
        terraform plan -destroy -out=tfdestroy
        terraform apply -auto-approve "tfdestroy"
        terraform workspace select default && terraform workspace delete $TF_WORKSPACE_NAME
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_cf_user: ${{ secrets.CF_USERNAME }}
        TF_VAR_cf_password: ${{ secrets.CF_PASSWORD }}
        TF_VAR_cf_space_name: 'teaching-vacancies-review'
        TF_VAR_app_docker_image: ${{ format('{0}:{1}', env.DOCKERHUB_REPOSITORY, github.sha) }}
        TF_VAR_app_stopped : true
        TF_VAR_papertrail_url: ${{ secrets.PAPERTRAIL_URL_DEV }}

    - name: Post PR comment
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      run: |
        curl --header "Accept: application/vnd.github.v3+json" \
             --header "Authorization: Bearer ${{ github.token }}" \
             --request POST \
             --data '{"body": "Review app deployed to https://${{ env.TF_VAR_web_app_name }}.london.cloudapps.digital"}' \
             https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments

    - name: Send slack message to twd_tv_dev channel
      uses: rtCamp/action-slack-notify@v2.0.2
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      env:
        SLACK_CHANNEL: twd_tv_dev
        SLACK_USERNAME: CI Deployment
        SLACK_ICON_EMOJI: ':tada:'
        SLACK_TITLE: Successful deployment
        SLACK_MESSAGE: 'Review app for PR ${{ github.event.number }} deployed to https://${{ env.TF_VAR_web_app_name }}.london.cloudapps.digital :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
