name: Smoke Test Manual

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true
        default: 'staging'

jobs:
  smoke-test-manual-job:
    name: Smoke Test Manual Job

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Set up ruby gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 20 --retry 3

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run smoke test
        run: bundle exec rspec spec/smoke_tests/job_seekers_can_view_homepage_${{ github.event.inputs.environment }}_spec.rb --tag smoke_test

      - name: Slack notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: twd_tv_dev
          SLACK_USERNAME: Smoke Test
          SLACK_ICON_EMOJI: ':cry:'
          SLACK_TITLE: Smoke test failed
          SLACK_MESSAGE: '${{ github.event.inputs.environment }} website smoke test has failed @channel'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
