name: Smoke Test workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  smoke-test:
    name: Smoke Test Production
    env:
      RAILS_ENV: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Trigger Smoke Test action
        id: smoke-test
        uses: ./.github/actions/smoke-test/
        with:
          aks_environment: 'production'
          event_name: ${{ github.event_name }}

      - name: Teams notification
        if: steps.smoke-test.conclusion != 'success'
        uses: DFE-Digital/github-actions/send-to-teams-channel@master
        with:
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: Smoke test failed
          service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
          message: |
            Smoke test failure in ${{ env.AKS_ENVIRONMENT}} environment
